### ISSUE TITLE
SyntaxError when building pure Python package with Extension

### ISSUE THREAD

**Issue by sergii-strelkovskyi** [ament/ament_tools#180] opened 2018-03-12 10:06 UTC
ament seems to mess up parsing of setup's arguments if there is anything other than string:

    sergii@s-strelkovskyi-d:/tmp/test_ament$ ament build
    # Topological order
     - ext_test

    Process package 'ext_test' with context:
    --------------------------------------------------------------------------------
     source_space => /tmp/test_ament/src/ext_test
      build_space => /tmp/test_ament/build/ext_test
    install_space => /tmp/test_ament/install
       make_flags => -j8, -l8
      build_tests => False
    --------------------------------------------------------------------------------
    +++ Building 'ext_test'
    Traceback (most recent call last):
      File "/opt/ros/ardent/bin/ament", line 9, in <module>
        load_entry_point('ament-tools==0.4.0', 'console_scripts', 'ament')()
      File "/opt/ros/ardent/lib/python3.5/site-packages/ament_tools/commands/ament.py", line 88, in main
        rc = args.main(args)
      File "/opt/ros/ardent/lib/python3.5/site-packages/ament_tools/verbs/build/cli.py", line 172, in main
        return iterate_packages(opts, packages, per_package_main)
      File "/opt/ros/ardent/lib/python3.5/site-packages/ament_tools/verbs/build/cli.py", line 300, in     iterate_packages
        rc = process_sequentially(jobs)
      File "/opt/ros/ardent/lib/python3.5/site-packages/ament_tools/verbs/build/cli.py", line 340, in     process_sequentially
        rc = job['callback'](job['opts'])
      File "/opt/ros/ardent/lib/python3.5/site-packages/ament_tools/verbs/build_pkg/cli.py", line 280, in main
        return run(opts, context)
      File "/opt/ros/ardent/lib/python3.5/site-packages/ament_tools/verbs/build_pkg/cli.py", line 331, in run
        handle_build_action(on_build_ret, context)
      File "/opt/ros/ardent/lib/python3.5/site-packages/ament_tools/verbs/build_pkg/cli.py", line 268, in handle_build_action
        for build_action in build_action_ret:
      File "/opt/ros/ardent/lib/python3.5/site-packages/ament_tools/build_types/ament_python.py", line 45, in on_build
        self._update_context_with_setup_arguments(context)
      File "/opt/ros/ardent/lib/python3.5/site-packages/ament_tools/build_types/ament_python.py", line 411, in _update_context_with_setup_arguments
        AmentPythonBuildType.build_type, context)
      File "/opt/ros/ardent/lib/python3.5/site-packages/ament_tools/setup_arguments.py", line 66, in get_setup_arguments_with_context
        return ast.literal_eval(output)
      File "/usr/lib/python3.5/ast.py", line 46, in literal_eval
        node_or_string = parse(node_or_string, mode='eval')
      File "/usr/lib/python3.5/ast.py", line 35, in parse
        return compile(source, filename, mode, PyCF_ONLY_AST)
      File "<unknown>", line 1
        {'version': '1.0.0', 'packages': [], 'name': 'test', 'ext_modules': [<setuptools.extension.Extension('test')     at 0x7f34a8887cc0>]}
                                                                             ^
    SyntaxError: invalid syntax
[test_ament.zip](https://github.com/ament/ament_tools/files/1802232/test_ament.zip)

**Comment by dhood** [comment] 2018-05-04 17:40
contributors interested in working on this are asked to contribute to [the `colcon` buildtool](https://github.com/colcon/colcon-core/) instead (provided that the issue still applies there)

**Comment by dirk-thomas** [comment] 2018-05-04 17:48
The problem is that "introspecting" the `setup()` arguments can only do so much. It probably needs to filter those out somehow since they are not relevant for getting metadata about the package.

**Comment by dirk-thomas** [comment] 2018-05-08 23:30
This will be fixed in the (soon to be announced) new build tool.

**Comment by mikaelarguedas** [comment] 2018-05-09 00:25
This is still an issue in ament_tools

**Comment by dirk-thomas** [comment] 2018-05-09 00:28
If nobody wants to do a "port" of the patch I would propose setting the label "wontfix" and close the issue.

**Comment by mikaelarguedas** [comment] 2018-05-09 00:34
That works too :+1:

**Closed** 2018-05-09 00:42 UTC
Labels: bug, wontfix
