### ISSUE TITLE
Failed to compile extension due to out-of-source build

### ISSUE THREAD

**Issue by sergii-strelkovskyi** [ament/ament_tools#181] opened 2018-03-16 13:23 UTC
Extesnion's source files are not linked during --symlink-install, resulting in compilation failure:

    sergii@s-strelkovskyi-d:/tmp/test_ament$ ament build --symlink-install
    # Topological order
     - ext_test
    
    Process package 'ext_test' with context:
    --------------------------------------------------------------------------------
     source_space => /tmp/test_ament/src/ext_test
      build_space => /tmp/test_ament/build/ext_test
    install_space => /tmp/test_ament/install
       make_flags => -j8, -l8
      build_tests => False
    --------------------------------------------------------------------------------
    +++ Building 'ext_test'
    +++ Installing 'ext_test'
    -- [ament] Deploying: /tmp/test_ament/install/share/ext_test/package.xml
    -- [ament] Deploying: /tmp/test_ament/install/share/ext_test/environment/ament_prefix_path.sh
    -- [ament] Deploying: /tmp/test_ament/install/share/ext_test/environment/path.sh
    -- [ament] Deploying: /tmp/test_ament/install/share/ext_test/environment/pythonpath.sh
    -- [ament] Deploying: /tmp/test_ament/install/share/ext_test/local_setup.bash
    -- [ament] Deploying: /tmp/test_ament/install/share/ext_test/local_setup.sh
    -- [ament] Deploying: /tmp/test_ament/install/share/ext_test/local_setup.zsh
    ==> '. /tmp/test_ament/build/ext_test/ament_python__install.sh && /usr/bin/python3 setup.py develop     --prefix /tmp/test_ament/install --no-deps' in '/tmp/test_ament/build/ext_test'
    running develop
    running egg_info
    creating dsst.egg-info
    writing dependency_links to dsst.egg-info/dependency_links.txt
    writing dsst.egg-info/PKG-INFO
    writing top-level names to dsst.egg-info/top_level.txt
    writing manifest file 'dsst.egg-info/SOURCES.txt'
    reading manifest file 'dsst.egg-info/SOURCES.txt'
    writing manifest file 'dsst.egg-info/SOURCES.txt'
    running build_ext
    building '_ext_test' extension
    creating build
    creating build/temp.linux-x86_64-3.5
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-    protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr    /include/python3.5m -c ext_test.c -o build/temp.linux-x86_64-3.5/ext_test.o
    x86_64-linux-gnu-gcc: error: ext_test.c: No such file or directory
    x86_64-linux-gnu-gcc: fatal error: no input files
    compilation terminated.
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    
    <== Command '. /tmp/test_ament/build/ext_test/ament_python__install.sh && /usr/bin/python3     setup.py develop --prefix /tmp/test_ament/install --no-deps' failed in '/tmp/test_ament/build/ext_test'     with exit code '1'
    <== Command '. /tmp/test_ament/build/ext_test/ament_python__install.sh && /usr/bin/python3     setup.py develop --prefix /tmp/test_ament/install --no-deps' failed in '/tmp/test_ament/build/ext_test'     with exit code '1'
[test_ament.zip](https://github.com/ament/ament_tools/files/1819299/test_ament.zip)

**Comment by dhood** [comment] 2018-05-04 17:26
@dirk-thomas do you think that this would still be an issue with colcon? If so I'll open an issue on `colcon-ros` instead of here, yeah?

**Comment by dhood** [comment] 2018-05-04 17:28
oh, actually maybe not colcon-ros, since this would happen for pure python packages too, and ament-python is deprecated, I remember now.

**Comment by dirk-thomas** [comment] 2018-05-04 17:35
I don't know. It needs to be tried. And if it still fails it can be ticketed there. More likely in `colcon-core` since Python packages are built by the core - the ROS package doesn't affect how the package is being processed.

**Comment by dirk-thomas** [comment] 2018-05-08 23:44
The problem is that in order to achieve an out-of-source build we invoke the `setup.py` with the cwd pointing to the `build` directory. We do that to avoid polluting the source folder of the package with any artifacts of the build process.

The same problem also happens when not using the symlink option since also in that case the build tool is doing an out-of-source build. (I updated the issue title based on that.)

I don't know if there is any way to achieve both (out-of-source build as well as build an extension) at the same time. If anybody has a suggestion on that it would be greatly appreciated.

**Comment by dirk-thomas** [comment] 2020-02-03 17:43
Closing since the repo is archived.

**Closed by dirk-thomas** 2020-02-03 17:43 UTC
Labels: help wanted
